rb-camera: add do_configure depends on virtual/kernel:do_shared_workdir
do_shared_workdir dependency is required to fix following error:

 mm-camera-interface/src/cam_intf.c:30:
  common/cam_intf.h:33:10: fatal error: media/msmb_isp.h: No such file or directory
  #include <media/msmb_isp.h>
           ^~~~~~~~~~~~~~~~~~

Change-Id: I72cff5f95d0dcc204875fe053abc91980f50fbc8